name: "Label merged PRs as hacktoberfest-accepted"

on:
  pull_request:
    types: [closed]

permissions:
  issues: write
  pull-requests: write

jobs:
  add-hacktoberfest-label:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Add or create hacktoberfest-accepted label
        uses: actions/github-script@v6
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue_number = context.payload.pull_request.number;
            const labelName = "hacktoberfest-accepted";

            try {
              await github.rest.issues.getLabel({
                owner,
                repo,
                name: labelName
              });
            } catch (err) {
              if (err.status === 404) {
                await github.rest.issues.createLabel({
                  owner,
                  repo,
                  name: labelName,
                  color: "0e8a16",
                  description: "PR accepted for Hacktoberfest"
                });
              } else {
                throw err;
              }
            }

            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: [labelName]
            });

            core = require('@actions/core');
            core.info(`Added label "${labelName}" to PR #${issue_number}`);
