name: Update Contributors

on:
  schedule:
    # This runs once every day at midnight UTC (around 5:30 AM in India).
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate contributors list
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          image_size: 100
          readme_path: CONTRIBUTORS.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update CONTRIBUTORS.md"
          branch: main
